# Generated by Django 3.1.7 on 2021-04-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('classTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('assignment_ID', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_no',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section_no',
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
