# Generated by Django 3.2 on 2021-05-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classTracker', '0004_auto_20210503_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classTracker.user'),
        ),
    ]
