# Generated by Django 3.2 on 2021-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classTracker', '0005_course_instructors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructors',
            new_name='instructor',
        ),
    ]
